### PR TITLE
Correct Sandi Metz's POODR title

### PR DESCRIPTION
**Pull request by pedrosmmoreira**
Corrects a small typo for the Practical Object-Oriented Design by Sandi Metz entry.

### CODE REVIEW

**Comment by scudelletti** [comment]
:+1:

**Comment by dreikanter** [comment]
Thanks!

**Comment by dreikanter** [comment]
Oops, wrong button :)

**Comment by pedrosmmoreira** [comment]
Glad to help, thank *you* for the great resource :)

**Pull request merged**
